---
dataset_config:
  splits:
    train: train
    eval: validation
    test: test
  load_dataset:
    path: amazon_reviews_multi
    name: en
  tokenizer:
    pretrained_model_name_or_path: bert-base-cased
  column_map:
    label_mapper: |
      lambda ex, tokenizer: dict(labels=int(ex['stars'])-1, **(tokenizer('. '.join([ex['review_title'], ex['review_body']]))))
    keep:
      - labels

model_config:
  pretrained_model_name_or_path: bert-base-cased
  num_labels: 5

trainer_config:
  num_train_epochs: 1
  output_dir: .
  do_eval: False
  do_train: True
